name: branchx
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  badges: ^2.0.3
  built_value: ^8.4.0
  cached_network_image: ^3.2.1
  carousel_slider: ^4.1.1
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.5
  cupertino_stepper: ^0.2.1

  device_info_plus: ^4.0.1
  dio: ^4.0.6
  dotted_border: ^2.0.0+2
  double_back_to_close_app: ^2.1.0
  fl_chart: ^0.55.1
  flutter:
    sdk: flutter
  flutter_neumorphic: ^3.2.0
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^1.1.4
  get: ^4.6.5
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  intl: ^0.17.0
  json_annotation: ^4.6.0
  logger: ^1.1.0
  numeric_keyboard: ^1.1.0
  pattern_formatter: ^2.0.0
  percent_indicator: ^4.2.2
#  permission_handler: ^10.0.0
  razorpay_flutter: ^1.3.0
  retrofit: ^3.0.1+1
  syncfusion_flutter_charts: ^20.3.48
  table_calendar: ^3.0.6
  url_launcher: ^6.1.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.2.0
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.9.3
  json_serializable: ^6.3.1
  retrofit_generator: ^4.0.3
  flutter_native_splash: ^2.2.5


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/img/
